In [1]:
import pandas as pd
df=pd.read_csv("rajasthan.csv")
df.head(10)

  Sl. No.   District  Civil  Criminal   Total
0       1      Ajmer  25696     71266   96962
1       2      Alwar  33446     98973  132419
2       3    Balotra   2177      7818    9995
3       4   Banswara   2508     17081   19589
4       5      Baran   3964     26701   30665
5       6     Barmer   8046     32900   40946
6       7     Beawer   9654     27333   36987
7       8  Bharatpur  15722     51736   67458
8       9   Bhilwara  17007     63210   80217
9      10    Bikaner  14568     44241   58809

In [2]:
#Load + column names + strp
df.columns=["Sl.No.","District","Civil","Criminal","Total"]
df["District"]=df['District'].str.strip()

In [3]:
#Total row alag karni hai + cleaning
state_total=df[df['District']=='Total']
df=df[df['District']!='Total'].copy()
df['District']=df['District'].replace({"Beawer":"Beawar"})
df=df.drop(columns="Sl.No.")

In [4]:
#check
assert(df['Civil']+df['Criminal']==df['Total']).all()
assert df['Total'].sum()==state_total['Total'].iloc[0]

In [6]:
#naye columns chahiye
df['Criminal_pct']=(df['Criminal']/df['Total']*100).round(1)
df["Civil_pct"]=(df["Civil"]/df["Total"]*100).round(1)
df["Share_of_State_pct"]=(df['Total']/df['Total'].sum()*100).round(2)
df['Rank']=df['Total'].rank(ascending=False).astype(int)
df['Pendency_band']=pd.qcut(df['Total'],3,labels=["Low","Medium","High"])

In [7]:
df.sort_values("Rank").to_csv("cleaned_rajasthan.csv",index=False)
df.sort_values("Rank").head(10)

,District,Civil,Criminal,Total,Criminal_pct,Civil_pct,Share_of_State_pct,Rank,Pendency_band
21,Jaipur Metro I,62564,296166,358730,82.6,17.4,14.03,1,High
22,Jaipur Metro II,35152,273920,309072,88.6,11.4,12.09,2,High
1,Alwar,33446,98973,132419,74.7,25.3,5.18,3,High
28,Jodhpur Metro,20960,94345,115305,81.8,18.2,4.51,4,High
43,Udaipur,17917,96535,114452,84.3,15.7,4.48,5,High
31,Kota,16763,86032,102795,83.7,16.3,4.02,6,High
0,Ajmer,25696,71266,96962,73.5,26.5,3.79,7,High
8,Bhilwara,17007,63210,80217,78.8,21.2,3.14,8,High
18,Ganganagar,15486,55305,70791,78.1,21.9,2.77,9,High
34,Pali,16037,51654,67691,76.3,23.7,2.65,10,High

In [8]:
out=df.sort_values("Rank").rename(columns={'Rank':"District_Rank"})
out.to_csv("rajasthan_for_sql.csv",index=False)